version: '3.7'
services:
    fieldsets-clickhouse:
        image: ${CONTAINER_REGISTRY:-fieldsets}/docker-clickhouse:${VERSION:-latest}
        build:
            context: ./
            dockerfile: ${CLICKHOUSE_CONFIG_PATH:-./}Dockerfile
            args:
                TIMEZONE: ${TIMEZONE:-America/New_York}
                CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION:-23}
                POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
                BUILD_CONTEXT_PATH: ${CLICKHOUSE_CONFIG_PATH:-./}
        container_name: fieldsets-clickhouse
        hostname: fieldsets-clickhouse
        environment:
            ENVIRONMENT: ${ENVIROMENT:-dev-local}
            VERSION: ${VERSION:-latest}
            TIMEZONE: ${TIMEZONE:-America/New_York}
            CLICKHOUSE_UID: ${LOCAL_UID:-1000}
            CLICKHOUSE_GID: ${LOCAL_GID:-1000}
            CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-172.28.0.5}
            CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-fieldsets}
            CLICKHOUSE_DB: ${CLICKHOUSE_DB:-fieldsets}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fieldsets}
            POSTGRES_HOST: ${POSTGRES_HOST:-172.28.0.7}
            POSTGRES_DB: ${POSTGRES_DB:-fieldsets}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
            DEBUG_MODE: ${DEBUG_MODE:-true}
            LOGGING_ENABLED: ${LOGGING_ENABLED:-false}
            FIELDSETS_LOCAL_HOST: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            - ${CLICKHOUSE_CONFIG_PATH:-./}users.xml:/etc/clickhouse-server/users.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}config.xml:/etc/clickhouse-server/config.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}named_collection.xml:/etc/clickhouse-server/config.d/named_collection.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}functions/:/etc/clickhouse-server/functions/
            - ${CLICKHOUSE_CONFIG_PATH:-./}initdb/:/docker-entrypoint-initdb.d/
            - ${FIELDSETS_PLUGINS_PATH:-./plugins/}:/fieldsets-plugins/
            - ${FIELDSETS_DATA_PATH:-./data/}:/fieldsets-data/
            - clickhouse-data:/var/lib/clickhouse
            - clickhouse-logs:/var/log/clickhouse-server
        ports:
            - ${CLICKHOUSE_PORT:-8123}:${CLICKHOUSE_PORT:-8123}
        networks:
            default:
                ipv4_address: ${CLICKHOUSE_HOST:-172.28.0.5}
        logging:
            driver: fluentd
            options:
                fluentd-address: ${LOGGER_HOST:-172.28.0.2}:${LOGGER_PORT:-24224}
                tag: debug_log.clickhouse
                fluentd-async: "true"
                env: "PGOPTIONS='-c search_path=pipeline',LOGGING_ENABLED='${LOGGING_ENABLED:-false}'"

volumes:
    clickhouse-data:
        driver: local
        name: fieldsets-clickhouse-data
    clickhouse-logs:
        driver: local
        name: fieldsets-clickhouse-logs

networks:
    default:
        driver: bridge
        name: fieldsets_network
        attachable: true
        ipam:
            config:
            - subnet: ${FIELDSETS_NETWORK_SUBNET:-172.28.0.0/24}