services:
    fieldsets-store:
        image: ${CONTAINER_REGISTRY:-fieldsets}/docker-clickhouse:${VERSION:-latest}
        build:
            context: ./
            dockerfile: ${CLICKHOUSE_CONFIG_PATH:-./}Dockerfile
            args:
                TIMEZONE: ${TIMEZONE:-America/New_York}
                CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION:-24}
                FIELDSETS_DB: ${FIELDSETS_DB:-postgres}
                FIELDSETS_DB_VERSION: ${FIELDSETS_DB_VERSION:-15}
                BUILD_CONTEXT_PATH: ${CLICKHOUSE_CONFIG_PATH:-./}
                LOCAL_UID: ${LOCAL_UID:-1000}
                LOCAL_GID: ${LOCAL_GID:-1000}
        container_name: fieldsets-store
        hostname: fieldsets-store
        cap_add:
            - SYS_NICE
            - NET_ADMIN
            - IPC_LOCK
        user: ${LOCAL_UID:-1000}:${LOCAL_GID:-1000}
        environment:
            ENVIRONMENT: ${ENVIROMENT:-dev-local}
            VERSION: ${VERSION:-latest}
            TIMEZONE: ${TIMEZONE:-America/New_York}
            ENABLE_DEBUG_MODE: ${ENABLE_DEBUG_MODE:-true}
            ENABLE_LOGGING: ${ENABLE_LOGGING:-false}
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
            CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS: 1
            CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-172.28.0.5}
            CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-fieldsets}
            CLICKHOUSE_DB: ${CLICKHOUSE_DB:-fieldsets}
            CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION:-24}
            FIELDSETS_DB: ${FIELDSETS_DB:-postgres}
            FIELDSETS_DB_USER: ${FIELDSETS_DB_USER:-postgres}
            FIELDSETS_DB_PASSWORD: ${FIELDSETS_DB_PASSWORD:-fieldsets}
            FIELDSETS_DB_HOST: ${FIELDSETS_DB_HOST:-172.28.0.7}
            FIELDSETS_DB_NAME: ${FIELDSETS_DB_NAME:-fieldsets}
            FIELDSETS_DB_PORT: ${FIELDSETS_DB_PORT:-5432}
            FIELDSETS_DB_VERSION: ${FIELDSETS_DB_VERSION:-15}
            FIELDSETS_LOCAL_HOST: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}
            FIELDSETS_CACHE_HOST: ${FIELDSETS_CACHE_HOST:-172.28.0.6}
            FIELDSETS_LOGGER_HOST: ${FIELDSETS_LOGGER_HOST:-172.28.0.2}
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            - ${CLICKHOUSE_CONFIG_PATH:-./}apt-preferences:/etc/preferences
            - ${CLICKHOUSE_CONFIG_PATH:-./}users.xml:/etc/clickhouse-server/users.d/fieldsets-users.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}config.xml:/etc/clickhouse-server/config.d/fieldsets-config.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}named_collection.xml:/etc/clickhouse-server/config.d/db_named_collection.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}initdb/:/docker-entrypoint-initdb.d/
            - ${CLICKHOUSE_CONFIG_PATH:-./}sql/:/usr/local/fieldsets/sql/
            - ${CLICKHOUSE_CONFIG_PATH:-./}plugins/:/usr/local/fieldsets/plugins/
            - ${CLICKHOUSE_CONFIG_PATH:-./}data/:/usr/local/fieldsets/data/
            - store-data:/var/lib/clickhouse
            - store-logs:/var/log/clickhouse-server
        ports:
            - ${CLICKHOUSE_PORT:-8123}:${CLICKHOUSE_PORT:-8123}

volumes:
    store-data:
        driver: local
        name: fieldsets-store-data
    store-logs:
        driver: local
        name: fieldsets-store-logs
