services:
    fieldsets-store:
        image: ${CONTAINER_REGISTRY:-fieldsets}/docker-clickhouse:${VERSION:-latest}
        build:
            context: ./
            dockerfile: ${CLICKHOUSE_CONFIG_PATH:-./}Dockerfile
            args:
                TIMEZONE: ${TIMEZONE:-America/New_York}
                CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION:-25.6}
                POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
                BUILD_CONTEXT_PATH: ${CLICKHOUSE_CONFIG_PATH:-./}
                LOCAL_UID: ${LOCAL_UID:-1000}
                LOCAL_GID: ${LOCAL_GID:-1000}
        container_name: fieldsets-store
        hostname: fieldsets-store
        cap_add:
            - SYS_NICE
            - NET_ADMIN
            - IPC_LOCK
        user: ${LOCAL_UID:-1000}:${LOCAL_GID:-1000}
        environment:
            ENVIRONMENT: ${ENVIROMENT:-dev-local}
            VERSION: ${VERSION:-latest}
            TIMEZONE: ${TIMEZONE:-America/New_York}
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
            CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS: 1
            CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-172.28.0.5}
            CLICKHOUSE_USER: ${CLICKHOUSE_USER:-fieldsets}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-fieldsets}
            CLICKHOUSE_DB: ${CLICKHOUSE_DB:-fieldsets}
            POSTGRES_USER: ${POSTGRES_USER:-fieldsets}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fieldsets}
            POSTGRES_HOST: ${POSTGRES_HOST:-172.28.0.7}
            POSTGRES_DB: ${POSTGRES_DB:-fieldsets}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
            ENABLE_DEBUG_MODE: ${ENABLE_DEBUG_MODE:-true}
            ENABLE_LOGGING: ${ENABLE_LOGGING:-false}
            FIELDSETS_LOCAL_HOST: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            - ${CLICKHOUSE_CONFIG_PATH:-./}apt-preferences:/etc/preferences
            - ${CLICKHOUSE_CONFIG_PATH:-./}users.xml:/etc/clickhouse-server/users.d/fieldsets-users.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}config.xml:/etc/clickhouse-server/config.d/fieldsets-config.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}named_collection.xml:/etc/clickhouse-server/config.d/db_named_collection.xml
            - ${CLICKHOUSE_CONFIG_PATH:-./}initdb/:/docker-entrypoint-initdb.d/
            - ${CLICKHOUSE_CONFIG_PATH:-./}sql/:/usr/local/fieldsets/sql/
            - ${CLICKHOUSE_CONFIG_PATH:-./}plugins/:/usr/local/fieldsets/plugins/
            - ${CLICKHOUSE_CONFIG_PATH:-./}data/:/usr/local/fieldsets/data/
            - store-data:/var/lib/clickhouse
            - store-logs:/var/log/clickhouse-server
        ports:
            - ${CLICKHOUSE_PORT:-8123}:${CLICKHOUSE_PORT:-8123}

volumes:
    store-data:
        driver: local
        name: fieldsets-store-data
    store-logs:
        driver: local
        name: fieldsets-store-logs
